# Using RamblingCookieMonster's Invoke-Parallel examples:
# https://ramblingcookiemonster.github.io/GitHub-Pester-AppVeyor/
# https://github.com/RamblingCookieMonster/Invoke-Parallel/blob/master/appveyor.yml
skip_commits:
  message: "([A|a]dd(ed)?|[U|u]pdate(d)?) ([R|r]eadme|[L|l]icense)" # One day I'll figure out how to case-insensitive patterns

build: false

install:
  - ps: . .\Build\build.ps1 -Task -Bootstrap

test_script:
  - ps: . .\Build\build.ps1 -Task "Test"