version: 0.1.0.{build}-{branch}

skip_commits:
  message: "([A|a]dd(ed)?|[U|u]pdate(d)?) ([R|r]eadme|[L|l]icense)" # One day I'll figure out how case-insensitive patterns

build: false

test_script:
  - ps: . .\Build\build.ps1 -Task "Test" -Bootstrap