---
name: Publish PowerShell Module
on:
  release:
    types: [created]
jobs:
  publish-to-gallery:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build and publish
      env:
        PSGalleryToken: ${{ secrets.PSGalleryToken }}
      shell: pwsh
      run: . ./Build/build.ps1 -Task Deploy -Bootstrap
...